name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install hexo-cli
        run: sudo npm install -g hexo

      - name: Configuration
        run: |
          git config --global user.name 'weekture'
          git config --global user.email 'focal.five@gmail.com'
          sed -i "s/__GITHUB_TOKEN__/${{ secrets.HEXO_DEPLOY_TOKEN }}/" _config.yml
          
      - name: Install node modules
        run: npm install
        
      - name: Clean hexo
        run: hexo clean

      - name: Generate hexo
        run: hexo generate
        
      - name: Deploy hexo
        run: hexo deploy
